### ISSUE TITLE
Can you help me install it?

### ISSUE THREAD

**Issue by hoangthonglx** [kuegi/kuegiBot#1]
I was installed successful simple bitmex, but with your bot, I cant instal! please help me how to install it :( ! thank bro

**Comment by kuegi** [comment]
as i wrote in the readme its not really easy to install and run it yourself right now and i would not recommend it.
This is a very specialised bot with strategies fit to my trading style. shouldn't be executed from scratch without understanding what it does, and it comes with literally no warranty whatsoever. so i would never let such a bot run on my money if i don't really understand what it does.

that being said: if you have all the dependencies installed (see readme) and a settingsfile in the settings folder, then running the cryptobot.py script as a daemon should do the trick. i will try to improve the documentation over the weekend.

but again: only run it with you understand what it does. otherwise just use the code as samples how a bot can be done and build your own version ;)

**Comment by kuegi** [comment]
Improved the usability and documentation quite a bit. Read the updated Readme.md for more information.
