### ISSUE TITLE
You are the stigma of a data scientist.

### ISSUE THREAD

**Issue by mdnaimul22** [kuegi/kuegiBot#17]
It is not right to think of yourself as something big. I'm looking at your closed pull request. If you doesn't want to help anyone, why you release this code on GitHub?
With a little guidance from you, many peoples could use it. Just You think that they're going back to with despair. It's not right. Disappointing of people is a kind of sin sin sin....Put your code into your laptop.

rm -rf kuegibot

Building a strong community
The primary purpose of the GitHub community is to collaborate on software projects. We want people to work better together. Although we maintain the site, this is a community we build together, and we need your help to make it the best it can be.

Be welcoming and open-minded - Other collaborators may not have the same experience level or background as you, but that doesn't mean they don't have good ideas to contribute. We encourage you to be welcoming to new collaborators and those just getting started.

**Comment by kuegi** [comment]
Is that your impression of "being open minded"? insulting and accusing of wrong things?

Thank you and bye.

For the record: i am completly open to any collaborator. But ppl like you are the reason that i question my descision to open source it. You think you are better because you accuse others of it? you are the discrace. stop the gate keeping and be nice.

if you have actual feedback: i am happy to answer any question and did so many times.
